.travis.yml
djoser/constants.py
djoser/views.py

Thank you for generously offering to consider a pull request!
I'll delete my fork if this is accepted.
I tweaked the travis.yml file so that combinations of Python 2.6 and Django 1.7 won't be tested. This is appropriate as Django 1.7 dropped support for Python 2.6.
It passes all Travis tests. See attached image.
Thank you!

Adding Python 2.6 support

---

djoser/utils.py

See here: https://github.com/django/django/blob/stable/1.8.x/django/contrib/auth/views.py#L234

urlsafe_base64_decode() decodes to bytestring on Python 3 so force_text needs to be used

---

djoser/utils.py

DRF 3.2.0 breaks djoser, because `request.DATA` is deprecated. See here: http://www.django-rest-framework.org/topics/3.2-announcement/

Fix deprecated DRF code

---

djoser/serializers.py
testproject/testapp/tests.py

Removed deprecated write_only_fields in DRF 3.2 and added style for the input password in the register browsable API

Fixed deprecated and added style for password

---

.travis.yml
README.md
djoser/urls/authtoken.py
djoser/urls/base.py
testproject/settings.py
testproject/urls.py
tox.ini

Improve TOX configuration. Now, dependencies are specified by a version range.
Rather than a version specified by a patch revision.
We don't need to commit anything when new patch revision becomes available.
To our taste, this is fair - testing all historical patches takes a lot of time
and end-users should use the newest revision always.
Remove deprecated django.conf.urls.patterns
This function is deprecated since Django 1.8. We remove usage of this
function for all supported Django versions. For more detail read:
https://docs.djangoproject.com/en/1.8/ref/urls/#patterns
Remove TEMPLATE_DIRS from testproject settings. This settings is deprecated in Django 1.8.
We remove this setting, because is not used in testproject, and is deprecated in Django 1.8.
This setting was required in Django …

Django 1.9 compatibility

---

djoser/constants.py
djoser/serializers.py
testproject/testapp/tests.py

We add invalid uid error message to UidAndTokenSerializer.
This serializer is used in ActivationView and PasswordResetConfirmView.

Human readable error message when incorrect uid is provided

---

.travis.yml
djoser/utils.py
djoser/views.py
testproject/testapp/tests.py
tox.ini

This PR essentialy rename `View.action` into `View._action` because `View.action` is a reserved attribute of DRF.
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/request.py#L56
This change is potentially backward incompatible, as such, a changelog entry should explain the steps and/or published with a major version bump (at the appreciation of the maintainers).
fixes #171

Add support for Drf 3.5

---

djoser/serializers.py
testproject/testapp/tests.py

Stumbled upon this piece of code and found it hard to read.
Now get method has only one responibility and loading serializers is
moved to __init__ method.

Initialize serializers dict on __init__ in SerializerManager

---

djoser/compat.py
djoser/serializers.py
docs/source/getting_started.rst
docs/source/settings.rst
testproject/settings.py
testproject/testapp/tests.py
testproject/testapp/validators.py
tox.ini

Remove support for DRF validators as password validators
Update documentation
Update tests
Based on #176 and #177

Add support for Django Password Validators

---

djoser/serializers.py

Didn't test, but should work because self.fields returns a dictionary.
Also if you read this, is there any documentation or explanation why it's necessary to rename the username key to new_username?

Simplified del to pop

---

djoser/views.py

https://github.com/sunscrapers/djoser/issues/223
Also renamed `active_users_kwargs` to `filter_users_kwargs`, and `active_users` to `filtered_users`, because the "active" word is no longer applicable. Feel free to change these variable names to something else if necessary.

Move User.is_active check from database to Python

---

djoser/urls/authtoken.py
djoser/urls/base.py
djoser/urls/jwt.py
docs/source/migration_guide.rst

Hi guys, your library isn't compatible with any frontend tools that strip trailing slashes from endpoints before making requests. This unfortunately means many Google tools, including Angular and most importantly, Chrome/Chromium. If you need to make `POST` requests to any of the endpoints, Django's `APPEND_SLASH` won't work as you lose the payload during the redirect.
This (minimal) pull request changes the regex to make the trailing slash optional on all of the urls.

Make trailing slash optional on all endpoints

---

docs/source/sample_usage.rst

Using the username/password provided, djoser throws the following error:
```
{"password":["The password is too similar to the username.","This password is too short. It must contain at least 8 characters."]}
```
The first logical change is to just use `password` for the password, but that errors with
```
{"password":["This password is too common."]}
```
The change I've proposed (`alpine12`) works with no issues.
**Note** - I'm not sure which branch to PR, project maintainers feel free to change the base branch or request that I do so.

Update example with working password

---

Pipfile
Pipfile.lock
djoser/views.py
docs/source/conf.py
requirements.txt
testproject/testapp/tests/test_user_view.py
testproject/urls.py

When the DRF docs try to inspect the UserViewSet, get_serializer_class
crashes because there's no request present. In such case, we should
fallback to the default serializer and everything should work as expected.
Signed-off-by: Antonis Kalipetis <akalipetis@gmail.com>

Add a test to make sure that DRF docs work

---

djoser/conf.py
djoser/serializers.py
djoser/views.py
docs/source/settings.rst
testproject/testapp/tests/test_user_view.py

This adds a new option `current_user` to `settings.SERIALIZERS` that allows different information to be returned from 'me' endpoints.
Currently a work in progress. See #294.

Split user serializers (fix #294)

---

djoser/permissions.py
djoser/views.py
testproject/testapp/tests/test_user_create.py

#303
default permission class in the `UserViewSet` allows any authenticated user to patch other `User` instances. I switched it to check object against request user.

[fix] allow update only current request user in UserViewSet

---

.travis.yml
README.rst
tox.ini

Update Travis testing for newer versions

---

docs/source/social_endpoints.rst

The proper usage of social auth endpoints was confusing. The full
workflow is now described in the documentation.
Fixes: #317

Added the social auth workflow

---

djoser/serializers.py
testproject/testapp/tests/test_user_create.py
testproject/testapp/validators.py

The code part of an error was previously lost when we converted from
django's ValidationError to DRF's ValidationError. Used the canonical
way of conversion to keep it.

Use canonical way of convering errors

---

djoser/serializers.py

After django==1.8 the authenticate method tests if user is active, so we
can drop the spurious test from djoser.
Fixes: #232

Remove spurious test of active user

---

testproject/testapp/tests/test_token_create.py

There was an old report that ``last_login`` is not updated when
obtaining the token. A test was added to ensure this feature.
Fixes: #261

Tested the last_login update

---

djoser/views.py

Actually use the `current_user` serializer from settings when it is set.
Fixes #349.

Fix broken current_user setting

---

djoser/templates/email/activation.html

A lot of JS fronend Framworks use & in the url. This leads to incorrect url that djoser sends to frontend.
Related Stackoverflow question https://stackoverflow.com/q/54797037/7986808
The answer we get with the following configuration:
`'ACTIVATION_URL': 'activate?id={uid}\u0026token={token}',`
Aswell as 
`'ACTIVATION_URL': 'activate?id={uid}&token={token}',`
```
Content-Type: multipart/alternative; boundary="===============2108040283=="
MIME-Version: 1.0
Subject: Account activation on l2Store
From: webmaster@localhost
To: aasddda@adasda.ur
Date: Thu, 21 Feb 2019 01:09:16 -0000
Message-ID: <155071135693.93536.10606728533257486545@khashashin.fritz.box>
--===============2108040283==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
You're receiving …
```

The url value on the template should take it as it is.

---

djoser/urls/base.py
djoser/views.py
docs/source/base_endpoints.rst
testproject/testapp/tests/test_user_create.py

The resend activation e-mail view that was provided by @sargo was added with documentation and tests.
Fixes: #168

Added the resend activation e-mail endpoint

---

djoser/locale/ka/LC_MESSAGES/django.po

The compilation of the Georgian translation raised an error of a missing argument « site_name » format. I fixed it, but since I don't speak Georgian, @zefciu could you confirm that the translation is still correct?

ka locale fixed missing site_name

---

CHANGELOG.rst
djoser/serializers.py
djoser/views.py
docs/source/base_endpoints.rst
testproject/testapp/models.py
testproject/testapp/tests/common.py
testproject/testapp/tests/test_activation.py
testproject/testapp/tests/test_password_reset.py
testproject/testapp/tests/test_password_reset_confirm.py
testproject/testapp/tests/test_set_username.py
testproject/testapp/tests/test_user_create.py

Following up on #382, this pull request replace 'email' in password-reset and activation-resend views with 'EMAIL_FIELD' field.
I also added some tests that checks djoser compatibility with custom user model by testing different endpoints with custom username, email and required fields.
I needed to use a lot of mock so the test cases aren't pretty, but changing the user model dynamically when the app has already loaded causes some conflicts and I didn't find a better solution. 
If this and #383 are both accepted, I'll handle the merge conflict between those two depending on the first one that get merged.

Custom email field for reset and resend views and custom user tests

---

CHANGELOG.rst
djoser/serializers.py
docs/source/base_endpoints.rst
testproject/testapp/tests/test_activation.py
testproject/testapp/tests/test_password_reset_confirm.py

Following up on #382, this pull request replace 'non_field_error' in password-reset-confirm and activation views with 'token' field error.

Remove non_field_error from base endpoints

---

djoser/conf.py
djoser/serializers.py
djoser/views.py
docs/source/base_endpoints.rst
docs/source/settings.rst
testproject/testapp/tests/test_user_create.py

I think that the user creation endpoint is missing a password confirmation option. Lots of websites ask twice for the password on registration

added USER_CREATE_PASSWORD_RETYPE option

---

docs/source/settings.rst

I noticed there was one endpoint that was still using the backward compatible url and the setting LOGOUT_ON_PASSWORD_CHANGE doesn't have any effect when you use JWT so I added a note about it.

Minor update to settings docs

---

docs/source/base_endpoints.rst

Fixed the default url for [user activation](https://github.com/sunscrapers/djoser/blob/master/djoser/views.py#L174) in the docs -- it's `/users/activation/`, not `/users/confirm/`

User Activation Doc Fix

---

djoser/views.py

We recently upgraded to the latest djoser version, and our test suite caught an issue with sending out confirmation emails after a user has been successfully activated. It turns out, the wrong email is sent in djoser's activate view.

Send the confirmation email after user activation

---

djoser/conf.py
djoser/serializers.py
djoser/views.py
docs/source/settings.rst
testproject/testapp/tests/test_user_delete.py
testproject/testapp/tests/test_user_view.py

My project requires primary key field of int(id) and guid field for User model. uuid field will used for only public operations. But currently djoser uses only primary key field. This simple changes make possible to configure the public id field.

ID_FIELD setting added

---

docs/source/base_endpoints.rst

Correct syntax error that was preventing the table from rendering properly.

Fix base_endpoints.rst User Activate table

---

docs/source/migration_guide.rst

There is a small typo in docs/source/migration_guide.rst.
Should read `endpoints` rather than `enpoints`.

docs: Fix simple typo, enpoints -> endpoints

---

djoser/views.py
testproject/testapp/tests/test_set_password.py

There's an issue on the `set_password` view when these three settings set True, all together.
`PASSWORD_CHANGED_EMAIL_CONFIRMATION`,
`LOGOUT_ON_PASSWORD_CHANGE`,
`CREATE_SESSION_ON_LOGIN`
An exception occurred because we log out the user at the first, so `request.user` set to `AnonymousUser`, next we try to send a confirmation email, what happens? can't find `EMAIL_FIELD` in `AnonymousUser` object.

Set Password Issue

---

Pipfile
Pipfile.lock
djoser/social/token/jwt.py
testproject/testapp/tests/social/test_provider_auth.py
testproject/testapp/tests/test_settings.py

Django 3.0 remove django.util.six. The bare six module works fine where it is used. This PR makes that change and also add `six` to Pipfile. Unfortunately, the Pipfile.lock change seems to be rather large.

use six directly instead of django.utils.six for Django 3.0

---

djoser/views.py
testproject/testapp/tests/test_set_password.py

Currently changing the user's password will invalidate the session regardless of settings.

set password should use CREATE_SESSION_ON_LOGIN key to keep user logged in

---

docs/source/social_endpoints.rst

I had to look at the source code to find the import to get the /o/{{ provider }}/ url working, 
including it in the documentation might help others save some time

Add urls.py config documentation for social auth

---

djoser/views.py

I was running into a similar (or same) issue as described here https://github.com/sunscrapers/djoser/issues/546. I had SEND_ACTIVATION_EMAIL=True and was updating a user's information that wasn't the email (i.e. first_name, last_name, etc). This resulted in sending an activation email, which doesn't really make sense since the email isn't being updated.
* Update user only sends email confirmation if email field was updated
* Updating fields other than the email result in NOT sending an activation email
* Keeps functionality of SEND_ACTIVATION_EMAIL
* All tests passed

Update user only sends email confirmation if email field was updated

---

djoser/serializers.py

It looks like after some changes, fixes introduced in #396 has been reversed. In one place key was again hardcoded instead of being imported from settings. This causes throwing KeyError when NON_FIELD_ERRORS_KEY is set to non-default value.

Replace hardcoded value for 'non_field_errors' with settings supplied variable

---

djoser/templates/email/password_reset.html
djoser/templates/email/username_reset.html

Before I made these changes, got emails with `&` replaced with `&amp;` between URL params

Safe urls in templates

---

docs/source/migration_guide.rst

The migration guide currently doesn't render correctly, either on Github or on the docs site: this PR fixes the formatting.﻿

Fix RST formatting in migration guide

---

djoser/serializers.py
djoser/views.py

Hi! I am using your perfect library for some time and I really thought there are still problems sending redundant emails when a user wants to update his/her info. I changed the code to only send activation email when user tries to change his/her email, as what is done in serializer and used that in views too. This PR is related to #546

send activation email only when email is changed

---

djoser/serializers.py

There will always be a user in the request object.  By default that user is AnonymousUser.  Django has built-in password validation that can valiate from the User object but is moot when validating from the AnonymousUser object.  Switching the order to first use the serializer's user allows for the use of the built-in Django validator django.contrib.auth.password_validation.UserAttributeSimilarityValidator.  Also wrap the self.user in a getattr just in case.

Use serializer user before request user for password validation

---

docs/source/sample_usage.rst

curl -X POST http://127.0.0.1:8088/auth/token/logout/ -H 'Authorization: Token b704c9fc3655635646356ac2950269f352ea1139 does not work.
The token has to be passed to the data request too.

Update logout doc

---

djoser/social/views.py

i forget add SOCIAL_AUTH_ALLOWED_REDIRECT_URIS to my config
it return 400 error, i don't know why ,  i pay more time find the issues
so  i add Friendly tips
-- sorry  , my english is not well
and thank you all

Fix for Friendly tips when Missing SOCIAL_AUTH_ALLOWED_REDIRECT_URIS

---

djoser/views.py

Example:
Assumption: User model requires extra arguments when a new user is created
With the current implementation, there's no way to supply these extra arguments without overriding AND duplicating most of perform_create's code
But now, it's possible override perform_create as follows:
def perform_create(self, serializer): # overrides djoser's perform_create
my_required_argument_to_create_a_user = 3.14159
some_more_args = request.something # say, a dict
return super().perform_create(serializer,my_required_argument_to_create_a_user=my_required_argument_to_create_a_user, **some_more_args)
------
For consistency, I added the same logic to perform_update.

Allow supplying extra arguments for serializer

---

docs/source/adjustment.rst
docs/source/authentication_backends.rst
docs/source/getting_started.rst
docs/source/social_endpoints.rst
docs/source/webauthn.rst

url() is deprecated and has been removed in Django v4

Replace url() with re_path() in the docs

---

.github/workflows/publish_pypi.yml

Closes https://github.com/sunscrapers/djoser/issues/824

Add compiled translations on Publish to PyPi Action. Closes #824

---

djoser/locale/fa/LC_MESSAGES/django.po
djoser/locale/fa_IR/LC_MESSAGES/django.po

Added Farsi (fa, fa_IR) translations to the Djoser authentication system.
- Introduced two locale directories: `fa` and `fa_IR`
- Added `django.po` files with Persian translations
- Localized authentication and email messages (e.g. login, signup, password reset)
This enables Djoser to support Persian users out of the box.

Add Persian locale support to Djoser (fa, fa_IR)

---

README.rst

This PR updates the version requirements in the README to accurately reflect the supported versions of Python (3.9–3.13), Django (3.2–5.2), and Django REST Framework (>=3.14).

Update README to Reflect Supported Python, Django, and DRF Versions
