djoser/serializers.py
Fix for issue https://github.com/sunscrapers/djoser/issues/21
=> _field_mapping -> serializer_field_mapping in djangorestframework 3.1.0

README.md
Changed `LOGIN_AFTER_ACTIVATION` to `LOGIN_AFTER_REGISTRATION` and remove some whitespaces in `README`
=> #54 change wrong setting in Register section in readme

djoser/serializers.py
This takes advantage of DRF's style argument, to protect password input in the browser api.
=> Give password field the input type of password

djoser/serializers.py, testproject/testapp/tests.py
Haven't seen any activity on #115, and it should definitely get fixed, so here is the change and a test.
Closes #114.
=> Set user activity to false if we fire an activation email

README.md, djoser/serializers.py, djoser/settings.py, djoser/views.py, testproject/testapp/tests.py, tox.ini
You can use own serializers by simple change settings.
We add SerializerFromSettingsMixin to utils module.
This mixin load serializer class from settings.
=> Introduced DJOSER.SERIALIZERS

README.md
Closes #40.
Excuse white space noise, my editor did it.
=> Add json web token docs

README.md
Hi guys,
First, nice work with Djoser, this lib help us a lot!
So, I did this PR to update a Customization documentation to use an existing method because `send_email` method does not exist in RegistrationView.
=> Change Customization topic example

requirements.txt
As mentioned in README - minimum Django version is 1.7
=> Fixed required Django version

djoser/utils.py
Fix code style issues according to PEP-8
=> Add arbitrary parameters to UserEmailFactoryBase

CHANGELOG.rst
=> Add release notes to CHANGELOG.rst

.travis.yml, CHANGELOG.rst, Makefile, Pipfile, Pipfile.lock, README.md, tox.ini
Add pipenv integration
Add Makefile to simplify setup and development
Remove support for Django 1.7
Remove support for DRF 3.3 as a consequence of dropping Django 1.7
Cleanup .travis.yml
Close #194
=> Add support for Python 3.6, Django 1.11, DRF 3.6

djoser/settings.py, djoser/templates/activation_email_body.html, djoser/templates/confirmation_email_body.html, djoser/templates/password_reset_email_body.html, djoser/utils.py
Hi, first of all thank you for this great piece of code! 
I had to send HTML E-Mails to my users, so I extended the settings and the EMailFactory classes to actually make use of the html_body_template_name field.
=> Integration of html e-mail templats

docs/source/examples.rst, docs/source/index.rst
=> Add examples chapter to docs for various edge cases users requests

djoser/compat.py, djoser/conf.py, djoser/serializers.py, djoser/views.py
=> Add USER_EMAIL_FIELD_NAME setting and compatibility function

djoser/conf.py, djoser/serializers.py, djoser/utils.py, docs/source/settings.rst, testproject/testapp/tests.py
Add SETTINGS_TO_IMPORT and _init_settings_to_import
Update {login|logout}_user with djoser.conf.settings.TOKEN_MODEL
Update TokenSerializer model with djoser.conf.settings.TOKEN_MODEL
Update docs to include information on TOKEN_MODEL
=> Add TOKEN_MODEL setting

djoser/serializers.py, djoser/utils.py, djoser/views.py, testproject/testapp/tests/test_set_username.py, testproject/testapp/tests/test_user_view.py
Add few tweaks and fixes
Add tests on activation and same username
=> Move SEND_ACTIVATION_EMAIL code to SetUsernameView

CHANGELOG.rst, docs/source/authentication_backends.rst
@piotr-szpetkowski adding these lines would have probably solved my issue. Feel free to pull in or not as you see fit. If you'd suggest any changes please let me know as well.
Thanks again for building this great library!
Fixes #240
=> Update docs for new URLConf in Djoser 1.0.0.

docs/source/sample_usage.rst
I noticed a typo error in the docs and I think it's better now !
=> Fix a typo error

djoser/views.py
=> Use partial_update for PATCH on /me

djoser/serializers.py
=> Fix cyclic import with CurrentUserSerializer

Pipfile.lock, requirements.txt, testproject/testapp/tests/test_activation.py, testproject/testapp/tests/test_password_reset_confirm.py, testproject/testapp/tests/test_set_password.py, testproject/testapp/tests/test_set_username.py, testproject/testapp/tests/test_user_view.py
=> Test errors: djet does not have utils module

djoser/conf.py, djoser/utils.py
=> Added session create/destroy option when login/logout

Pipfile, Pipfile.lock, README.rst, djoser/social/serializers.py, djoser/social/token/jwt.py, djoser/social/views.py, djoser/urls/jwt.py, docs/source/authentication_backends.rst, docs/source/getting_started.rst, requirements.txt, testproject/settings.py, testproject/testapp/tests/social/test_provider_auth.py, testproject/testapp/tests/social/test_token_jwt.py
=> Use django-rest-framework-simplejwt instead of django-rest-framework-jwt

djoser/constants.py
https://writingexplained.org/log-in-or-login-difference
=> fixed grammar: 'to login' -> 'to log in'

docs/source/authentication_backends.rst, docs/source/jwt_endpoints.rst, docs/source/migration_guide.rst
Thanks to @peterkmurphy for his efforts in troubleshooting this.
=> Update docs for JWT framework migration

djoser/utils.py
=> Add **kwargs to ActionViewmixin.post() handler

README.rst, setup.py, tox.ini
=> Add Django 2.2 to supported and tested configurations

djoser/views.py
Current version on `master` does not support Python 2.7.
=> Fix failing tests for Python 2.7

djoser/views.py, testproject/testapp/tests/test_user_create.py, testproject/testapp/tests/test_user_detail.py, testproject/testapp/tests/test_user_list.py
=> Prevent non-staff users from getting other users data

djoser/locale/fr/LC_MESSAGES/django.po, djoser/locale/ka/LC_MESSAGES/django.po, djoser/locale/pl/LC_MESSAGES/django.po, djoser/locale/ru_RU/LC_MESSAGES/django.po, djoser/templates/email/activation.html
I wrote the French translation file and I also moved out the `<p/>` tag that was erroneously inside a `{% blocktrans %}` in `confirmation.html` (I also removed the now superfluous translation in all other translation files).
=> French translation

docs/source/base_endpoints.rst
I fixed some errors in the request params (USERNAME_FIELD was used in some place instead of uid and email field) and I added missing error response code and content
=> Base endpoints docs correction

djoser/urls/jwt.py, docs/source/authentication_backends.rst
#392 resolution and more details on available `simplejwt` settings from `djoser`.
=> Update simplejwt settings docs

docs/source/authentication_backends.rst
Add minimalistic documention for session authentication.
Address #398
=> Add documention for session authentication

docs/source/settings.rst
`CurrentUserSerializer` was deprecated
=> Fix serializer name in doc

testproject/testapp/tests/test_set_password.py, testproject/testapp/tests/test_set_username.py, testproject/testapp/tests/test_user_delete.py, testproject/testapp/tests/test_user_detail.py, testproject/testapp/tests/test_user_me.py, testproject/testapp/tests/test_user_view.py, tox.ini
* Changed the settings in testproject to use the `CurrentUserOrAdminOrReadOnly` permissions
* Changed the tests accordingly
* Removed the `user` parameter from client calls that served no purpose
=> Tested all the permission schemas

README.rst
Update video in README and add info about TokenCreateSerializer behaviour.
=> Update README and new instruction video

djoser/locale/de/LC_MESSAGES/django.po
I did aim for consistency within the translated messages.
It should be understandable in any case and I tried to be as polite as the original. Other German users should feel free to adjust for shorter or common lingo if necessary.
=> German translation

djoser/locale/pt_BR/LC_MESSAGES/django.po
Added brazilian portuguese translation.
=> Translation - pt-BR

djoser/locale/es/LC_MESSAGES/django.po
=> Translation - es

djoser/views.py, tox.ini
=> Fix compatibility issue with drf 3.12

README.rst, docs/source/getting_started.rst, poetry.lock, pyproject.toml, tox.ini
fixes #628 
add django 3.2 support
=> add django 3.2 support

djoser/locale/fr/LC_MESSAGES/django.po
I have used the following command to update french translation: 
```
poetry run django-admin makemessages -l fr
```
and i have added the missing translations.
=> Update french translation

README.rst
=> Typo resolved in README

djoser/locale/ja/LC_MESSAGES/django.po
I added Japanese translations, but I'm not sure if I did it correctly. (I couldn't locally compile the test project since poetry kept raising an error upon compilation.) 
Let me know if I'm missing anything.
=> add the japanese translations

.github/workflows/publish_pypi.yml
Closes # https://github.com/sunscrapers/djoser/issues/726
=> add publish_pypi.yml GH action

djoser/templates/email/activation.html
Rewrote the activation email since the previous one could be improved upon
=> Rewrite activation email template

.github/workflows/test-suite.yml
closes https://github.com/sunscrapers/djoser/issues/732
=> add on open pull_request trigger GH action test-suite

djoser/templates/email/activation.html
Reverts sunscrapers/djoser#731
=> Revert "Rewrite activation email template"

.github/workflows/test-suite.yml, pyproject.toml
Closes https://github.com/sunscrapers/djoser/issues/741
=> add Django 4.2 to the CI test matrix

.github/workflows/test-suite.yml, pyproject.toml
Closes https://github.com/sunscrapers/djoser/issues/772
=> run tests on prerelease django 5

djoser/social/urls.py, djoser/urls/authtoken.py, djoser/urls/jwt.py, djoser/webauthn/urls.py
This reverts commit 16f406e9
Closes https://github.com/sunscrapers/djoser/issues/778
=> Revert "replace re_path with path"

djoser/email.py, pyproject.toml, testproject/settings.py, testproject/testapp/tests/test_email.py, testproject/testapp/tests/test_user_create.py
Closes https://github.com/sunscrapers/djoser/issues/846
=> remove django-templated-mail from dependencies
